const lesson1 = {

  id: "lesson1",

  title: "Introduction to Text Machine Learning",

  content: `

Lesson 01

Introduction to Text Machine Learning


1. Introduction


A large portion of the information generated by people is stored as text.


Examples include:


Reviews.


Emails.


Messages.


Articles.


Reports.


Support tickets.


Product descriptions.


Search queries.



2. What Is Text Machine Learning?


Text machine learning applies machine learning techniques to textual information.


The basic objective is:


Text


→


Numerical representation


→


Machine learning model


→


Prediction or discovery.



3. Why Text Is Different


A numerical dataset might contain:


Age = 21.


Income = 50000.


Score = 0.82.



4. Text Example


A document may contain:


"The camera produces excellent images but the battery is weak."



5. Problem


A machine learning algorithm cannot directly use the sentence as ordinary numerical input.


We need a representation.



6. Text as Data


A document can be treated as a collection of linguistic units.


These may include:


Characters.


Words.


Tokens.


Sentences.



7. Document


A document is a unit of text that is treated as one observation.


For example:


One customer review.


One email.


One news article.



8. Corpus


A corpus is a collection of documents used for analysis or machine learning.



9. Example Corpus


Document 1:


"The product is excellent."



Document 2:


"The product arrived late."



Document 3:


"The product is excellent and affordable."



10. Documents as Samples


In supervised learning, each document can represent one sample.



11. Labels


A document can have a target label.



12. Example


Review:


"The product is excellent."


Label:


Positive.



13. Another Example


Review:


"The product arrived damaged."


Label:


Negative.



14. Text Classification


Text classification assigns one or more predefined categories to text.



15. Examples


Spam detection:


Spam / Not Spam.



16. Sentiment Classification


Positive / Negative.



17. News Classification


Politics.


Sports.


Technology.


Business.



18. Support Tickets


Billing.


Technical.


Account.


Delivery.



19. Text Regression


Text can also be used to predict numerical values.


Example:


Predict a rating from a review.



20. Unsupervised Text Learning


Text can also be analyzed without target labels.



21. Examples


Document clustering.


Topic discovery.


Similarity search.



22. Feature Extraction


The central challenge is converting text into numerical features.



23. Example


Vocabulary:


["fast", "good", "slow"].



24. Document


"fast good"



25. Vector


[1, 1, 0].



26. Interpretation


The vector indicates:


fast = present.


good = present.


slow = absent.



27. Vocabulary


The vocabulary is the collection of terms used as features.



28. Vocabulary Size


If a dataset contains:


10,000 unique terms.


a basic word-based representation may contain:


10,000 dimensions.



29. Sparse Vectors


Most individual documents contain only a small fraction of the vocabulary.


Therefore most vector values are zero.



30. Sparse Example


Suppose vocabulary size:


10,000.



A document may contain:


20 unique terms.



31. Result


Approximately:


9,980.


features may have value zero.



32. Why Sparse Data Matters


Sparse representations allow text systems to work with large vocabularies efficiently.



33. Basic Text ML Workflow


Text


↓


Preprocessing


↓


Vectorization


↓


Model


↓


Prediction.



34. Text Preprocessing


Possible operations include:


Lowercasing.


Removing unnecessary characters.


Handling whitespace.


Tokenization.



35. Important Warning


Preprocessing is not automatically beneficial simply because it is common.


A transformation should be used when it helps the particular problem.



36. Example


Consider:


"Excellent!"


and:


"excellent"



37. Lowercasing


Both can become:


"excellent".



38. Potential Benefit


The vocabulary becomes smaller.



39. Potential Cost


Case information is lost.



40. Machine Learning Representation


After vectorization:


Document


→


Vector.



41. Mathematical View


For vocabulary:


V = {w₁, w₂, ..., wₙ}



A document can be represented as:


x = [x₁, x₂, ..., xₙ]



42. Meaning


xᵢ represents some property of word wᵢ in the document.



43. Count Representation


One simple representation uses:


xᵢ = number of occurrences of wᵢ.



44. Example


Vocabulary:


["good", "product", "slow"].



Document:


"good product good"



45. Count Vector


[2, 1, 0].



46. Why Count?


The vector records how frequently each vocabulary term occurs.



47. Python Library


scikit-learn provides:


CountVectorizer.



48. Import


Python


from sklearn.feature_extraction.text import (

    CountVectorizer

)



49. Example Dataset


Python


documents = [

    "the product is good",

    "the product is fast",

    "the product is good and fast"

]



50. Create Vectorizer


Python


vectorizer = CountVectorizer()



51. Fit and Transform


Python


X = vectorizer.fit_transform(

    documents

)



52. Vocabulary


Python


print(

    vectorizer.get_feature_names_out()

)



53. Matrix


Python


print(

    X.toarray()

)



54. Interpretation


Each row represents one document.


Each column represents one vocabulary term.



55. Shape


Python


print(

    X.shape

)



56. Example Interpretation


If:


X.shape = (3, 7)



Then:


3 documents.


7 vocabulary features.



57. Why Vectorization?


Machine learning algorithms require numerical input.


Vectorization converts text into numerical features.



58. Text Classification Example


Suppose we have:


Review 1:


"excellent product"



Label:


1.



59. Review 2


"poor quality"



Label:


0.



60. Model


A classifier can learn:


Text features


→


Class label.



61. Important Concept


The model does not understand language in the same way a human does.


It learns statistical relationships in the numerical representation.



62. Example


If words such as:


excellent.


amazing.


useful.


appear frequently in positive training examples, a classifier may learn that these features are associated with the positive class.



63. Context Limitation


A simple word-count representation does not fully understand:


Grammar.


Meaning.


Sarcasm.


Long-range relationships.



64. Example


Consider:


"The product is not good."



65. Challenge


The word:


good.


may appear strongly associated with positive reviews.


But:


"not good"


has a different meaning.



66. Why Representation Matters


The quality of the text representation influences what patterns the model can learn.



67. Text Features


Common representations include:


Bag-of-Words.


TF-IDF.


N-grams.


Word embeddings.



68. Bag-of-Words


Represents documents using word occurrence information.



69. TF-IDF


Weights terms according to their importance within documents and across the corpus.



70. N-Grams


Represent sequences of words or characters.



71. Embeddings


Represent words, sentences, or documents as dense vectors designed to capture useful relationships.



72. Classical vs Modern Text ML


Classical approaches:


Bag-of-Words.


TF-IDF.


Linear models.


Naive Bayes.



73. Modern Approaches


Modern NLP often uses:


Neural networks.


Transformers.


Pretrained language models.



74. This Module


This module focuses primarily on practical classical text machine learning techniques and real-world workflows.



75. Real-World Example


Imagine a company receives:


10,000 support tickets.



76. Manual Process


Employees manually assign categories.



77. Machine Learning Process


Text ticket


↓


Vectorization


↓


Classifier


↓


Predicted category.



78. Possible Categories


Billing.


Technical support.


Account.


Delivery.



79. Business Value


A text classifier can help route incoming tickets automatically.



80. Evaluation


The classifier can be evaluated using:


Precision.


Recall.


F1.


Confusion matrix.



81. Experiment


Create a small collection of positive and negative reviews.



82. Step 1


Store documents in a Python list.



83. Step 2


Create CountVectorizer.



84. Step 3


Transform the documents.



85. Step 4


Inspect the vocabulary.



86. Step 5


Inspect the document-term matrix.



87. Step 6


Train a simple classifier.



88. Step 7


Evaluate predictions.



89. Common Mistakes


Mistake 1:


Treating raw text as numerical features without vectorization.


Mistake 2:


Removing too much information during preprocessing.


Mistake 3:


Ignoring vocabulary size.


Mistake 4:


Evaluating only training performance.


Mistake 5:


Assuming word frequency completely captures meaning.



90. Practice


1. What is text machine learning?


2. What is a document?


3. What is a corpus?


4. What is text classification?


5. What is vectorization?


6. What is a vocabulary?


7. Why are text vectors often sparse?


8. What does CountVectorizer do?


9. What is Bag-of-Words?


10. Why can simple word counts miss context?



91. Quick Check


Question 1


Why must text usually be converted into numerical features?


Answer:


Most classical machine learning algorithms require numerical input.



Question 2


What does each row of a document-term matrix represent?


Answer:


One document.



Question 3


What does each column represent?


Answer:


A vocabulary feature or term.



92. Summary


Text machine learning transforms textual information into representations that machine learning algorithms can process.


Important concepts include:


Documents.


Corpora.


Vocabulary.


Vectorization.


Sparse representations.


Bag-of-Words.


TF-IDF.


Text classification.



93. Extended Study


Text machine learning can be viewed as a representation problem.


The original observation is:


D = text document.


A vectorization function transforms it:


φ(D) = x.


The machine learning model then learns:


f(x) → y.



94. Final Reflection


Whenever you work with text, ask:


What is one observation?


What is the target?


What vocabulary should be used?


How should text be represented?


Which information might be lost?


Which evaluation metric matches the problem?


These questions form the foundation of practical text machine learning.

`

};

export default lesson1;