export const courses = [
  {
    id: 1,
    title: "Frontend Development",
    instructor: "CloudLearn AI",
    lessons: 82,
    completed: 59,
    duration: "10 Weeks",
    level: "Beginner",
    progress: 72,
    category: "Programming",
  },
  {
    id: 2,
    title: "Cloud Computing",
    instructor: "CloudLearn AI",
    lessons: 96,
    completed: 40,
    duration: "12 Weeks",
    level: "Intermediate",
    progress: 41,
    category: "Cloud",
  },
  {
    id: 3,
    title: "Python Programming",
    instructor: "CloudLearn AI",
    lessons: 75,
    completed: 18,
    duration: "8 Weeks",
    level: "Beginner",
    progress: 24,
    category: "Programming",
  },
];