import {
  Brain,
  Cloud,
  ShieldCheck,
  Database,
  Code2,
  Cpu,
  Smartphone,
  Globe,
  Blocks,
  Network,
} from "lucide-react";

export const domains = [
  {
    title: "Cloud Computing",
    description: "AWS, Azure, Docker, Kubernetes & DevOps",
    lessons: 120,
    duration: "12 Weeks",
    level: "Intermediate",
    icon: Cloud,
  },
  {
    title: "Artificial Intelligence",
    description: "Generative AI, LLMs & Intelligent Systems",
    lessons: 95,
    duration: "14 Weeks",
    level: "Advanced",
    icon: Brain,
  },
  {
    title: "Programming",
    description: "C, C++, Python, JavaScript & Java",
    lessons: 150,
    duration: "16 Weeks",
    level: "Beginner",
    icon: Code2,
  },
  {
    title: "Data Science",
    description: "Python, Pandas, NumPy & Machine Learning",
    lessons: 110,
    duration: "13 Weeks",
    level: "Intermediate",
    icon: Database,
  },
  {
    title: "Cyber Security",
    description: "Ethical Hacking & Network Security",
    lessons: 90,
    duration: "10 Weeks",
    level: "Intermediate",
    icon: ShieldCheck,
  },
  {
    title: "Machine Learning",
    description: "Regression, Classification & Deep Learning",
    lessons: 100,
    duration: "15 Weeks",
    level: "Advanced",
    icon: Cpu,
  },
  {
    title: "Android Development",
    description: "Flutter & Kotlin Development",
    lessons: 85,
    duration: "10 Weeks",
    level: "Beginner",
    icon: Smartphone,
  },
  {
    title: "Full Stack Development",
    description: "React, Next.js, Node.js & MongoDB",
    lessons: 140,
    duration: "16 Weeks",
    level: "Intermediate",
    icon: Globe,
  },
  {
    title: "Blockchain",
    description: "Web3, Smart Contracts & Solidity",
    lessons: 75,
    duration: "9 Weeks",
    level: "Advanced",
    icon: Blocks,
  },
  {
    title: "Networking",
    description: "CCNA, Routing & Switching",
    lessons: 80,
    duration: "10 Weeks",
    level: "Intermediate",
    icon: Network,
  },
];