const lesson1 = {
  id: "lesson1",
  moduleId: "module1",
  lessonNumber: 1,

  title: "What Is Generative AI?",

  subtitle:
    "Understand the foundations, evolution, architecture, probability, training, inference, and real-world ecosystem of Generative AI.",

  description:
    "This lesson builds a complete mental model of Generative AI. You will learn how Generative AI fits inside Artificial Intelligence, Machine Learning, and Deep Learning; how generative models differ from predictive models; how generation works probabilistically; how training and inference differ; what foundation models are; and how modern Generative AI applications are constructed.",

  estimatedTime: "90–120 min",

  difficulty: "Beginner → Intermediate",

  learningObjectives: [
    "Define Artificial Intelligence, Machine Learning, Deep Learning, Generative AI, and foundation models.",
    "Explain where Generative AI fits within the broader AI hierarchy.",
    "Distinguish discriminative or predictive models from generative models.",
    "Understand the idea of learning a data distribution.",
    "Explain how a generative model produces a new output from learned patterns.",
    "Understand the difference between training and inference.",
    "Explain the role of parameters θ in a machine learning model.",
    "Understand conditional and unconditional generation.",
    "Understand why probability is fundamental to generative modeling.",
    "Identify the major modalities handled by modern Generative AI systems.",
    "Understand the relationship between foundation models, applications, tools, and user interfaces.",
    "Develop a practical mental model for building Generative AI applications."
  ],

  overview: `
Generative AI refers to a family of artificial intelligence systems that learn patterns from data and use those learned patterns to produce new content. The generated content may be text, images, audio, video, code, structured data, or combinations of multiple modalities.

The word "generative" is important. Traditional machine learning systems are frequently designed to predict a label, estimate a value, detect an object, or make a decision. Generative systems are instead designed to model the structure of data sufficiently well that they can produce new samples that follow the learned patterns.

A language model, for example, does not simply store a collection of sentences and retrieve one of them whenever a user asks a question. During training, its parameters are adjusted so that the model learns statistical relationships between tokens. During inference, those learned parameters are used to calculate probabilities for possible next tokens. A sequence is generated by repeatedly selecting tokens according to the model's probability distribution and the application's decoding strategy.

This makes Generative AI fundamentally probabilistic. A model can assign different probabilities to different possible outputs, and generation can therefore be viewed as a process of sampling from a learned distribution.

Generative AI is not a completely separate field from Artificial Intelligence. It is built on decades of research in machine learning, probability, optimization, neural networks, representation learning, computer vision, natural language processing, and distributed computing.

A useful hierarchy is:

Artificial Intelligence
→ Machine Learning
→ Deep Learning
→ Generative Modeling
→ Foundation Models
→ Generative AI Applications

This hierarchy is not a strict mathematical taxonomy. It is a practical way to understand how modern Generative AI developed from earlier AI disciplines.

At the application level, a modern Generative AI product usually contains much more than a model. It can include a user interface, authentication, prompt construction, retrieval, databases, vector search, tool execution, model inference, output validation, monitoring, safety controls, and business logic.

Therefore, learning Generative AI requires two complementary perspectives.

The first is the model perspective: how neural networks represent information, learn parameters, estimate probabilities, and generate outputs.

The second is the systems perspective: how models are connected to applications, external data, tools, APIs, databases, and users.

This course will progressively develop both perspectives.
`,

  sections: [
    {
      id: "ai-hierarchy",
      title: "1. Artificial Intelligence → Machine Learning → Deep Learning → Generative AI",

      content: `
Artificial Intelligence is the broad field concerned with building systems that perform tasks associated with intelligent behavior. These tasks may include perception, reasoning, planning, language understanding, decision making, prediction, and generation.

Machine Learning is a major approach within Artificial Intelligence. Instead of manually writing every rule required to solve a problem, a machine learning system learns patterns from examples.

For example, a traditional rule-based spam detector might contain rules such as "if an email contains certain words, classify it as spam." A machine learning spam classifier can instead learn statistical relationships between features and labels from a dataset containing examples of spam and non-spam messages.

Deep Learning is a subfield of Machine Learning based primarily on neural networks with multiple computational layers. Deep neural networks can learn increasingly abstract representations of data.

Generative modeling is a branch of machine learning in which the objective involves learning the structure or distribution of observed data so that new samples can be generated.

Modern Generative AI systems often use deep neural networks and large-scale training datasets. Large language models, diffusion models, multimodal transformers, and other foundation models are examples of modern generative systems.

It is useful to remember that these categories overlap. A generative model can be a deep learning model, and a deep learning model can be used for either predictive or generative tasks.
`,

      process: [
        "Artificial Intelligence provides the broad problem-solving field.",
        "Machine Learning allows systems to learn patterns from data.",
        "Deep Learning uses multi-layer neural networks to learn representations.",
        "Generative Modeling learns structures that can support the creation of new samples.",
        "Foundation Models learn broad reusable representations from large datasets.",
        "Generative AI applications connect models to users, data, tools, and software systems."
      ],

      bullets: [
        "AI is the broadest category.",
        "Machine Learning is one major approach to AI.",
        "Deep Learning is a subfield of Machine Learning.",
        "Generative modeling focuses on learning data structure for generation.",
        "Foundation models provide reusable capabilities across many downstream tasks.",
        "Applications combine models with software engineering components."
      ]
    },

    {
      id: "predictive-vs-generative",
      title: "2. Predictive Models vs Generative Models",

      content: `
One of the most important distinctions in Generative AI is the difference between predicting an outcome and generating a new sample.

Suppose we have a dataset containing images of cats and dogs. A predictive classifier can receive an image x and calculate a probability such as:

P(y = cat | x)

The model is interested in predicting the label y given the input x.

A generative model approaches the data differently. It attempts to learn aspects of the underlying data distribution so that it can produce new samples that resemble the distribution.

For example, a generative image model may learn patterns involving shapes, textures, colors, spatial relationships, and higher-level visual structures. During generation, those learned relationships can be used to produce a new image.

The difference can be summarized conceptually:

Predictive model:
Input → prediction

Generative model:
Learned distribution → new sample

This distinction is not absolute because many modern systems can perform both predictive and generative tasks. The important point is to understand the objective of the model and what probability distribution it is attempting to estimate.
`,

      comparisonTable: {
        title: "Predictive Models vs Generative Models",
        columns: [
          "Aspect",
          "Predictive Model",
          "Generative Model"
        ],
        rows: [
          [
            "Primary goal",
            "Predict or classify an outcome",
            "Generate new samples"
          ],
          [
            "Typical task",
            "Classification or regression",
            "Text, image, audio, video, or code generation"
          ],
          [
            "Example",
            "Spam classification",
            "Text generation"
          ],
          [
            "Typical probability",
            "P(y|x)",
            "P(x) or P(x,y)"
          ],
          [
            "Output",
            "Label, score, or prediction",
            "New content or sampled data"
          ]
        ]
      },

      examples: [
        "A sentiment classifier predicts whether a review is positive or negative.",
        "A house-price model predicts a numerical price.",
        "A language model generates a sequence of tokens.",
        "A diffusion model generates an image.",
        "A music generation model produces an audio sequence."
      ]
    },

    {
      id: "data-distribution",
      title: "3. The Central Idea: Learning a Data Distribution",

      content: `
The mathematical idea behind generative modeling begins with probability distributions.

Imagine a dataset containing millions of examples. Those examples are not random in the completely uniform sense. They have structure.

Human language contains grammatical relationships. Images contain spatial relationships. Music contains temporal patterns. Source code contains syntax and semantic relationships.

A generative model attempts to learn a mathematical representation of these patterns.

If the data is represented by a random variable X, we can describe the underlying data distribution as:

P(X)

A trained generative model attempts to learn a parameterized approximation of this distribution:

pθ(x)

Here θ represents the learnable parameters of the model.

The parameters are not individual examples stored in a simple database. They are numerical values distributed throughout the neural network. Training changes these values so that the model becomes better at representing the statistical structure of the training data.

The goal can therefore be understood conceptually as:

Training data
→ learn parameters θ
→ obtain a model pθ(x)
→ use pθ(x) to generate samples

The quality of generation depends on how effectively the learned model captures useful structure in the training distribution.
`,

      formula:
        "pθ(x) ≈ pdata(x)",

      examples: [
        "For language, x may represent a sequence of tokens.",
        "For an image model, x may represent a high-dimensional pixel or latent representation.",
        "For audio, x may represent a waveform or learned acoustic representation.",
        "For code, x may represent a token sequence following programming-language structure."
      ]
    },

    {
      id: "probability-generation",
      title: "4. Why Probability Is Fundamental to Generative AI",

      content: `
Generative AI is deeply connected to probability because a model often needs to represent uncertainty over possible outputs.

Consider the sentence:

"The student opened the"

A language model may assign probabilities to several possible next tokens:

book
door
laptop
window
application

The probabilities need not be equal. The model uses the context to estimate which continuations are more plausible.

For a sequence of tokens x₁, x₂, ..., xₜ, the probability of the entire sequence can be factorized using the chain rule of probability.

This gives:

P(x₁, x₂, ..., xₜ)
=
∏ₜ P(xₜ | x₁, ..., xₜ₋₁)

This equation is fundamental to autoregressive language modeling.

It says that the probability of an entire sequence can be represented as a product of conditional next-token probabilities.

During generation, the model repeatedly calculates a distribution over possible next tokens and selects one according to the decoding strategy.

This means generation is not usually one giant operation. It is an iterative process.

Context
→ probability distribution
→ choose next token
→ append token
→ update context
→ calculate next distribution
→ repeat
`,

      formula:
        "P(x₁, x₂, ..., xₜ) = ∏ₜ P(xₜ | x₁, ..., xₜ₋₁)",

      examples: [
        "If the current context is 'The capital of France is', the model can assign high probability to 'Paris'.",
        "If the context is 'A neural network contains', possible continuations may include 'layers', 'parameters', or 'neurons'.",
        "Generation continues until an end condition such as an end-of-sequence token or maximum length is reached."
      ]
    },

    {
      id: "parameters-theta",
      title: "5. What Does θ Represent?",

      content: `
The symbol θ is commonly used to represent the learnable parameters of a machine learning model.

A neural network can contain millions, billions, or even hundreds of billions of parameters depending on the architecture and model scale.

A parameter is typically a numerical value such as a weight or bias. During training, optimization algorithms modify these values so that the model's predictions become better according to a chosen objective.

We can describe a model as:

ŷ = fθ(x)

Here:

x represents the input.

f represents the model function.

θ represents the learned parameters.

ŷ represents the model output.

Training attempts to find parameter values that minimize an objective function.

A simplified optimization expression is:

θ* = argminθ L(θ)

where L represents the loss function.

This notation is extremely important throughout Generative AI because later lessons will discuss optimization, gradient descent, backpropagation, transformers, embeddings, attention, fine-tuning, and parameter-efficient adaptation.

The parameters themselves are not human-readable rules. A large neural network does not normally contain a simple list such as "if the user says this, respond with that." Instead, knowledge and patterns are distributed across a very large numerical parameter space.
`,

      formula:
        "ŷ = fθ(x)",

      examples: [
        "A neural network weight may determine how strongly one learned feature contributes to another computation.",
        "During training, gradients provide information about how parameters should change.",
        "After training, θ is fixed for ordinary inference unless the model is being fine-tuned or adapted."
      ]
    },

    {
      id: "training-vs-inference",
      title: "6. Training vs Inference",

      content: `
Training and inference are two fundamentally different phases of a machine learning system.

Training is the process through which model parameters are learned or updated. It generally requires large datasets, optimization algorithms, substantial compute, and repeated forward and backward computations.

Inference is the process of using an already-trained model to produce predictions or generated outputs.

For a language model, training may involve processing enormous quantities of token sequences. The model predicts tokens, compares predictions against training targets, calculates a loss, computes gradients, and updates parameters.

Inference usually does not update the model's parameters. Instead, the learned parameters are used to calculate outputs for new input.

The distinction can be visualized as:

Training:
Data
→ preprocessing
→ model
→ prediction
→ loss
→ gradients
→ parameter update
→ repeat

Inference:
Input
→ model with fixed parameters
→ output probabilities
→ decoding
→ generated output

Training can be extremely computationally expensive because the model may need to process massive datasets across many GPUs or other accelerators.

Inference has a different optimization problem. A production application may need low latency, high throughput, memory efficiency, batching, caching, quantization, and efficient serving infrastructure.
`,

      process: [
        "Collect and prepare training data.",
        "Convert data into a representation usable by the model.",
        "Run a forward pass.",
        "Calculate the training objective or loss.",
        "Calculate gradients.",
        "Update model parameters θ.",
        "Repeat across many batches and training steps.",
        "Freeze or save the resulting model for inference.",
        "Provide new inputs during inference.",
        "Generate outputs using the learned parameters."
      ],

      comparisonTable: {
        title: "Training vs Inference",
        columns: [
          "Aspect",
          "Training",
          "Inference"
        ],
        rows: [
          [
            "Purpose",
            "Learn model parameters",
            "Use learned parameters"
          ],
          [
            "Parameters",
            "Updated",
            "Normally fixed"
          ],
          [
            "Main inputs",
            "Training dataset",
            "User or application input"
          ],
          [
            "Optimization",
            "Central requirement",
            "Usually not performed"
          ],
          [
            "Compute pattern",
            "Forward + backward passes",
            "Primarily forward computation"
          ],
          [
            "Typical goal",
            "Improve model capability",
            "Produce useful outputs efficiently"
          ]
        ]
      }
    },

    {
      id: "conditional-generation",
      title: "7. Conditional and Unconditional Generation",

      content: `
Generative models can operate without an explicit condition or can generate content conditioned on additional information.

Unconditional generation attempts to sample from a learned distribution without a user-provided condition.

For example, an image generator might produce an image from random latent noise:

z → generator → x

Conditional generation introduces an additional condition c.

The model can then be viewed conceptually as:

P(x|c)

where c may be text, an image, a class label, audio, metadata, or another representation.

Text-to-image generation is a clear example. The condition can be a text prompt describing the desired image.

Text generation can also be viewed conditionally because the next token depends on the preceding context.

For example:

P(xₜ | x₁, ..., xₜ₋₁)

The context acts as the condition for predicting the next token.

Conditional generation is one of the foundations of modern multimodal AI systems because different input modalities can be used to control the generated output.
`,

      formula:
        "P(x|c)",

      examples: [
        "Text → image generation",
        "Text → text generation",
        "Image → image transformation",
        "Audio → text generation",
        "Text → audio generation",
        "Code context → code completion"
      ]
    },

    {
      id: "foundation-models",
      title: "8. Foundation Models",

      content: `
A foundation model is a large model trained on broad and diverse data so that its learned capabilities can support many downstream tasks.

Instead of building a separate model from scratch for every application, developers can use a pretrained foundation model as a starting point.

A language foundation model may learn representations and statistical relationships from large quantities of text and code. A multimodal foundation model may learn relationships across text, images, audio, or video.

The important idea is reuse.

A pretrained model can be adapted through prompting, fine-tuning, retrieval augmentation, tool use, or other techniques.

The resulting application may therefore contain:

Foundation model
+
Application instructions
+
User context
+
External data
+
Tools
+
Validation
+
User interface

This is why the model itself is only one component of a modern Generative AI product.
`,

      process: [
        "Large-scale data collection and preparation",
        "Pretraining a general-purpose model",
        "Evaluation and capability analysis",
        "Optional instruction tuning or adaptation",
        "Application-specific prompting",
        "Optional retrieval or tool integration",
        "Application deployment and monitoring"
      ]
    },

    {
      id: "modalities",
      title: "9. Generative AI Across Different Modalities",

      content: `
Generative AI is not limited to text.

A modality is a type of information such as text, image, audio, or video.

Text generation models operate over language tokens.

Image generation systems may operate over pixels, latent representations, or other visual representations.

Audio generation systems model temporal acoustic information.

Video generation must represent both spatial and temporal structure.

Multimodal systems connect multiple modalities so that information can flow between them.

For example:

Text → Image

Image → Text

Audio → Text

Text → Audio

Text + Image → Text

Text + Image → Video

The underlying model architectures may differ, but the central principle remains similar: learn useful representations and relationships from data, then use those learned relationships to produce new outputs.
`,

      table: {
        title: "Generative AI Modalities",
        columns: [
          "Modality",
          "Input Example",
          "Generated Output"
        ],
        rows: [
          [
            "Text",
            "Prompt",
            "Text"
          ],
          [
            "Image",
            "Text prompt",
            "Image"
          ],
          [
            "Audio",
            "Text or audio context",
            "Speech or sound"
          ],
          [
            "Video",
            "Text or multimodal context",
            "Video"
          ],
          [
            "Code",
            "Natural language or code context",
            "Source code"
          ],
          [
            "Multimodal",
            "Text + image + audio",
            "Text, image, audio, or combined output"
          ]
        ]
      }
    },

    {
      id: "application-architecture",
      title: "10. From Model to Complete Generative AI Application",

      content: `
A common beginner mistake is to think that a Generative AI application is simply a model connected to a text box.

In production, the architecture is usually much richer.

A user interacts with a frontend. The frontend communicates with an application backend. The backend validates the request, constructs the model input, retrieves relevant information when necessary, calls an AI model, validates the generated response, stores appropriate information, and returns the result.

A simplified architecture is:

User
→ Frontend
→ Backend API
→ Prompt / Context Construction
→ Retrieval or Tools
→ Generative Model
→ Output Validation
→ Backend
→ Frontend
→ User

Each layer has a different responsibility.

The model generates language or other content.

The application code controls business rules.

The database stores application state.

Retrieval systems provide external knowledge.

Tools allow the model-driven workflow to interact with external systems.

Validation prevents malformed or unsafe outputs from automatically reaching downstream systems.

Observability allows developers to understand failures and measure system performance.

This separation of responsibilities becomes increasingly important as Generative AI applications move from prototypes to production.
`,

      process: [
        "User submits a request.",
        "Frontend sends the request to the backend.",
        "Backend validates input and authentication.",
        "Application constructs instructions and context.",
        "Retrieval or tools provide additional information when needed.",
        "Generative model produces a candidate output.",
        "Application validates and transforms the output.",
        "Application stores required state or telemetry.",
        "Backend returns the result.",
        "Frontend displays the result."
      ],

      examples: [
        "A learning assistant can combine a language model with course content and a progress database.",
        "A customer-support assistant can combine a model with company policies, retrieval, authentication, and human escalation.",
        "A coding assistant can combine a model with source files, static analysis, testing tools, and repository context."
      ]
    },

    {
      id: "mathematical-intuition",
      title: "11. Mathematical Intuition: What Is a Generative Model Actually Learning?",

      content: `
The phrase "the model learns from data" can sound vague. A more precise view is that the model learns parameter values that allow a mathematical function to represent useful statistical relationships in the data.

Suppose a training dataset contains samples:

D = {x₁, x₂, ..., xₙ}

The model has parameters θ.

Training attempts to find values of θ that make the model's behavior useful according to a chosen objective.

For likelihood-based generative modeling, one common objective is to maximize the likelihood of observed training examples.

Conceptually:

θ* = argmaxθ ∑ᵢ log pθ(xᵢ)

The logarithm is commonly used because products of probabilities become sums of log probabilities, which are easier to optimize numerically.

An equivalent loss formulation is:

L(θ) = -∑ᵢ log pθ(xᵢ)

Training then attempts to minimize L(θ).

This does not mean the model memorizes every possible future output. Instead, optimization changes the parameters so that the model assigns useful probability mass to patterns present in the training distribution.

For a language model, this idea becomes next-token prediction.

For a diffusion model, the learning objective is related to transforming noisy representations toward useful data representations.

For other generative model families, the mathematical objective may take a different form.

The details differ, but the common principle is:

Data
→ objective
→ optimization
→ learned parameters θ
→ model distribution or transformation
→ generation
`
    },

    {
      id: "worked-example",
      title: "12. Worked Example: How a Language Model Generates Text",

      content: `
Consider the prompt:

"The sky is"

The language model converts the input into tokens.

The tokens are transformed into numerical representations.

The transformer processes those representations and produces a probability distribution over possible next tokens.

Suppose the simplified distribution is:

blue: 0.45
clear: 0.20
dark: 0.10
beautiful: 0.05
other tokens: 0.20

The model does not necessarily have to select the highest-probability token. The decoding strategy determines how the distribution is converted into an actual choice.

If "blue" is selected, the sequence becomes:

"The sky is blue"

The model then processes the updated context and calculates another distribution.

The next token might be:

today
above
and
.

The process continues until the generation terminates.

Therefore, text generation can be understood as repeated conditional probability estimation.

At each step:

Current context
→ model
→ logits
→ probability distribution
→ decoding
→ next token
→ updated context

This repeated process is one of the central mechanisms behind autoregressive language generation.
`,

      process: [
        "Tokenize the input context.",
        "Convert tokens into model representations.",
        "Process the sequence through the model.",
        "Produce logits for possible next tokens.",
        "Convert logits into probabilities.",
        "Apply a decoding strategy.",
        "Select the next token.",
        "Append the token to the context.",
        "Repeat until a stopping condition is reached."
      ],

      formula:
        "P(xₜ | x₁, ..., xₜ₋₁)",

      examples: [
        "Context: 'The sky is' → possible next token: 'blue'.",
        "Context: 'Machine learning is' → possible next tokens may include 'powerful', 'useful', or 'a'.",
        "Context changes after every generated token, so the probability distribution changes at every step."
      ]
    },

    {
      id: "generation-control",
      title: "13. How Generation Is Controlled",

      content: `
The model's probability distribution does not by itself determine the final output. The generation system also uses a decoding strategy.

Temperature is one common control. Conceptually, temperature changes the sharpness of the probability distribution.

A lower temperature tends to make high-probability tokens more dominant.

A higher temperature can make lower-probability alternatives more likely to be selected.

Other decoding methods include greedy decoding, top-k sampling, and nucleus sampling.

Greedy decoding selects the highest-probability token at each step.

Top-k sampling restricts the candidate set to the k most probable tokens.

Nucleus sampling, often called top-p sampling, selects from a dynamically sized set whose cumulative probability reaches a specified threshold.

These controls demonstrate an important principle: model knowledge and generation behavior are related but not identical.

The same underlying model can produce different outputs depending on the decoding strategy.
`,

      comparisonTable: {
        title: "Common Decoding Strategies",
        columns: [
          "Strategy",
          "Basic Idea",
          "Typical Behavior"
        ],
        rows: [
          [
            "Greedy",
            "Select highest-probability token",
            "Deterministic and focused"
          ],
          [
            "Temperature sampling",
            "Adjust distribution sharpness",
            "Controls randomness"
          ],
          [
            "Top-k",
            "Sample only from k candidates",
            "Limits candidate space"
          ],
          [
            "Top-p",
            "Sample from cumulative probability mass",
            "Dynamic candidate set"
          ]
        ]
      }
    },

    {
      id: "real-world-ecosystem",
      title: "14. The Modern Generative AI Ecosystem",

      content: `
Modern Generative AI is an ecosystem rather than a single technology.

At the foundation are datasets, compute infrastructure, model architectures, optimization algorithms, and training systems.

Above the trained models are model-serving systems and APIs.

Application developers then build systems using prompts, retrieval, tools, databases, structured outputs, agents, and user interfaces.

A simplified ecosystem is:

Data
→ Training infrastructure
→ Foundation model
→ Model serving
→ Application logic
→ Retrieval / tools
→ User interface
→ Users

Around this stack are evaluation, observability, security, governance, cost management, and safety mechanisms.

A strong Generative AI engineer therefore needs more than prompt-writing skills. The engineer needs to understand model behavior, software architecture, data, APIs, evaluation, debugging, deployment, and system reliability.

This course will progressively move from foundations toward these engineering concerns.
`,

      process: [
        "Data and datasets",
        "Model architecture",
        "Training and optimization",
        "Foundation model",
        "Inference and model serving",
        "Application backend",
        "Retrieval and external knowledge",
        "Tools and integrations",
        "Frontend and user experience",
        "Evaluation, monitoring, and governance"
      ]
    },

    {
      id: "common-misconceptions",
      title: "15. Common Misconceptions About Generative AI",

      content: `
Generative AI is often described using simplified statements that can create incorrect mental models.

One misconception is that a language model is simply a database of sentences. In reality, modern neural language models learn distributed numerical representations and statistical relationships through optimization.

Another misconception is that generated text is guaranteed to be factual because it is produced by a powerful model. Generation quality and factual accuracy are separate concerns. A model can produce fluent text that contains incorrect information.

Another misconception is that increasing the number of parameters automatically solves every problem. Larger models can provide stronger capabilities, but quality also depends on training data, objective, architecture, optimization, inference methods, context, retrieval, evaluation, and application design.

A final misconception is that Generative AI applications consist only of prompts. Production systems typically require software engineering around the model.

Understanding these distinctions is essential before moving into LLMs, transformers, embeddings, prompting, RAG, and AI agents.
`,

      bullets: [
        "Generative AI is not simply a database lookup system.",
        "Fluent generation does not guarantee factual correctness.",
        "More parameters do not automatically solve every application problem.",
        "A production AI system is more than a model and a prompt.",
        "Application-level validation remains important.",
        "Evaluation must be based on measurable behavior rather than impressive demonstrations alone."
      ]
    }
  ],

  codeExamples: [
    {
      title: "A Minimal Probabilistic Text Generator",
      language: "python",
      code: `import random

next_tokens = {
    "the": {
        "cat": 0.6,
        "dog": 0.3,
        "student": 0.1
    },
    "cat": {
        "runs": 0.5,
        "sleeps": 0.3,
        "jumps": 0.2
    }
}

def sample_next_token(context):
    distribution = next_tokens.get(
        context,
        {"the": 1.0}
    )

    tokens = list(distribution.keys())
    probabilities = list(distribution.values())

    return random.choices(
        tokens,
        weights=probabilities,
        k=1
    )[0]

context = "the"

for _ in range(5):
    token = sample_next_token(context)
    print(token)
    context = token
`
    },

    {
      title: "Representing a Model With Parameters θ",
      language: "python",
      code: `import numpy as np

# A tiny illustrative model.
# Real neural networks contain many more parameters.

theta = np.array([
    0.8,
    -0.3,
    0.5
])

x = np.array([
    1.0,
    2.0,
    -1.0
])

bias = 0.2

y_hat = np.dot(theta, x) + bias

print("Model output:", y_hat)
`
    },

    {
      title: "Simple Conditional Generation Concept",
      language: "python",
      code: `def generate_response(task):
    if task == "code":
        return "Generate a programming solution."
    elif task == "explanation":
        return "Generate a conceptual explanation."
    elif task == "summary":
        return "Generate a concise summary."
    else:
        return "Request clarification."

print(generate_response("code"))
`
    }
  ],

  mathIntuition: [
    {
      title: "Probability Distribution",
      explanation: `
A probability distribution represents uncertainty over possible outcomes.

For a language model, the possible outcomes at one generation step are vocabulary tokens. The model assigns a probability to each candidate token.

The probabilities form a distribution:

∑ᵢ P(xᵢ | context) = 1

The model therefore does not simply say "this token is correct." It assigns relative likelihoods to possible continuations.
`
    },

    {
      title: "Likelihood and Log-Likelihood",
      explanation: `
Suppose a dataset contains examples x₁, x₂, ..., xₙ.

A likelihood-based objective can be written as:

L(θ) = ∏ᵢ pθ(xᵢ)

Multiplying many small probabilities can create numerical difficulties, so logarithms are commonly used:

log L(θ) = ∑ᵢ log pθ(xᵢ)

Training can then maximize log-likelihood or equivalently minimize negative log-likelihood:

J(θ) = -∑ᵢ log pθ(xᵢ)

This connects probability, optimization, and model training.
`
    },

    {
      title: "Parameter Optimization",
      explanation: `
A simplified optimization view is:

θ* = argminθ J(θ)

The training algorithm searches for parameter values that reduce the objective.

Gradient-based optimization uses the derivative of the objective with respect to the parameters:

∇θ J(θ)

A simplified gradient-descent update is:

θ ← θ - η∇θ J(θ)

where η is the learning rate.

The learning rate controls the size of each parameter update.
`
    }
  ],

  exercises: [
    {
      question:
        "Explain the difference between Artificial Intelligence, Machine Learning, Deep Learning, and Generative AI.",
      difficulty: "Easy"
    },
    {
      question:
        "Explain why generative modeling is connected to probability distributions.",
      difficulty: "Medium"
    },
    {
      question:
        "Explain the difference between P(y|x) and P(x).",
      difficulty: "Medium"
    },
    {
      question:
        "Why are training and inference different computational phases?",
      difficulty: "Medium"
    },
    {
      question:
        "Explain the meaning of θ in a neural network.",
      difficulty: "Medium"
    },
    {
      question:
        "Describe conditional generation and give three examples.",
      difficulty: "Medium"
    },
    {
      question:
        "Explain why a production Generative AI application requires more than a model.",
      difficulty: "Hard"
    }
  ],

  codingExercises: [
    {
      title: "Build a Simple Token Sampler",
      description:
        "Create a Python program containing a small vocabulary and probability distribution. Sample the next token several times and observe how different probabilities influence the output.",
      difficulty: "Easy"
    },
    {
      title: "Implement Temperature Scaling",
      description:
        "Implement a Python function that receives logits and a temperature value and converts the adjusted logits into probabilities using softmax.",
      difficulty: "Medium"
    },
    {
      title: "Build a Tiny Conditional Generator",
      description:
        "Create a Python program that generates different responses depending on a supplied condition such as task type, topic, or output format.",
      difficulty: "Medium"
    },
    {
      title: "Implement a Small Gradient Update",
      description:
        "Create a tiny numerical example demonstrating θ ← θ - η∇θJ(θ). Print the parameter value before and after the update.",
      difficulty: "Medium"
    }
  ],

  architectureExercises: [
    {
      title: "Design a Generative AI Application",
      description:
        "Draw an architecture containing a frontend, backend API, prompt construction layer, generative model, database, retrieval component, validation layer, and monitoring.",
      difficulty: "Medium"
    },
    {
      title: "Training vs Inference Architecture",
      description:
        "Create two separate flow diagrams showing the major stages of model training and model inference.",
      difficulty: "Medium"
    },
    {
      title: "Multimodal Generation Architecture",
      description:
        "Design a system that accepts text and image inputs and generates a textual response. Identify the responsibilities of each system component.",
      difficulty: "Hard"
    }
  ],

  interviewQuestions: [
    "What is Generative AI?",
    "How is Generative AI different from traditional predictive machine learning?",
    "Where does Generative AI fit within Artificial Intelligence?",
    "What is a generative model?",
    "What does it mean for a model to learn a data distribution?",
    "What is the difference between P(y|x) and P(x)?",
    "What does θ represent in a machine learning model?",
    "What is the difference between training and inference?",
    "What is conditional generation?",
    "What is a foundation model?",
    "Why is probability important in language generation?",
    "What is autoregressive generation?",
    "Why does a production Generative AI application need components beyond the model?",
    "What are the major modalities handled by Generative AI?",
    "Why does fluent generated text not guarantee factual correctness?"
  ],

  commonMistakes: [
    "Thinking Generative AI is simply a database that retrieves stored examples.",
    "Confusing prediction with generation.",
    "Assuming that a generative model produces deterministic outputs in every situation.",
    "Ignoring the role of probability in generation.",
    "Confusing training with inference.",
    "Assuming that θ represents one single value rather than a collection of model parameters.",
    "Assuming that more parameters automatically guarantee better application performance.",
    "Assuming that a foundation model alone is a complete AI application.",
    "Assuming that fluent language is automatically factual.",
    "Ignoring application-level validation and evaluation.",
    "Treating prompts as the entire Generative AI engineering stack."
  ],

  summary: `
Generative AI is a major area of modern Artificial Intelligence focused on systems that learn patterns from data and use those learned patterns to generate new content.

The field is built on Artificial Intelligence, Machine Learning, Deep Learning, probability, optimization, neural networks, representation learning, and large-scale computing.

The central mathematical idea is that a model with parameters θ learns a useful approximation to patterns in a data distribution.

For language generation, the probability of a sequence can be decomposed into conditional next-token probabilities:

P(x₁, x₂, ..., xₜ)
=
∏ₜ P(xₜ | x₁, ..., xₜ₋₁)

Training learns the parameters. Inference uses those parameters to produce outputs.

Modern Generative AI systems operate across text, images, audio, video, code, and multimodal data. Foundation models provide broad reusable capabilities, while application systems add prompts, retrieval, tools, databases, validation, user interfaces, and business logic.

The most important mental model is therefore:

Data
→ Learning
→ Parameters θ
→ Model
→ Inference
→ Generated output
→ Application system
→ User
`,

  keyTakeaways: [
    "Generative AI learns patterns from data and uses them to generate new content.",
    "Generative modeling is deeply connected to probability distributions.",
    "Predictive models often estimate outcomes, while generative models model data structure for generation.",
    "θ represents the learnable parameters of a model.",
    "Training learns or updates parameters; inference normally uses fixed parameters.",
    "Autoregressive generation repeatedly predicts conditional next-token probabilities.",
    "Conditional generation uses additional information to control the generated output.",
    "Foundation models provide reusable capabilities for many downstream applications.",
    "A Generative AI application contains much more than the underlying model.",
    "Probability, optimization, neural networks, data, and software engineering are all important foundations for Generative AI.",
    "Fluent generation should not automatically be interpreted as factual correctness.",
    "The rest of the Generative AI course builds from these foundations toward LLMs, transformers, prompting, RAG, embeddings, APIs, multimodal systems, and production engineering."
  ]
};

export default lesson1;
