const lesson4 = {

  id: "lesson4",

  title: "The catch Block",

  content: `

# The catch Block


## Introduction


The catch block is the second important component of exception handling in C++.

It is used to handle exceptions generated by the throw statement.


While the try block detects an exception, the catch block provides the solution for handling that exception.



## What is catch Block?


A catch block contains the code that executes when an exception occurs.


It receives the exception object thrown by the throw statement and performs appropriate actions.



## Syntax


catch(exceptionType variableName)

{

    // Exception handling code

}



The exception type in catch must match the type of exception thrown.



## Working of catch Block


The execution process:


1. Program enters the try block.

2. An exception occurs.

3. The throw statement sends the exception.

4. Control moves to the matching catch block.

5. Catch block handles the exception.



## Example Program


#include<iostream>

using namespace std;


int main()

{

    int number;


    cout<<"Enter number: ";

    cin>>number;


    try

    {

        if(number == 0)

        {

            throw number;

        }


        cout<<"Valid Number";

    }


    catch(int)

    {

        cout<<"Exception: Zero value is not allowed";

    }


    return 0;

}



Output:


Enter number: 0

Exception: Zero value is not allowed



## Multiple catch Blocks


A program can contain multiple catch blocks to handle different types of exceptions.


Example:


try

{

    // risky code

}


catch(int)

{

    // integer exception

}


catch(string)

{

    // string exception

}



The compiler selects the matching catch block.



## Catching All Exceptions


C++ provides a special catch block:


catch(...)

{

    // handles any exception

}



It can handle exceptions of any type.



## Advantages of catch Block


The catch block provides:


### Error Recovery

Allows the program to respond to errors.


### Better Control

Program flow can be managed after an exception.


### Meaningful Messages

Users receive understandable error information.


### Program Stability

Prevents unexpected termination.



## Real-World Applications


catch blocks are used in:


### Banking Systems

Handling:

- Invalid transactions.
- Account errors.


### File Handling

Handling:

- Missing files.
- Access errors.


### Database Applications

Handling:

- Connection failures.
- Query errors.



## Key Points


Remember:


- catch handles exceptions.
- It works with try and throw.
- Exception type must match.
- Multiple catch blocks are possible.


The catch block completes the exception handling mechanism by providing a way to safely handle runtime errors.

`

};


export default lesson4;