const lesson12 = {
  id: "lesson12",

  title: "break Statement",

  content: [
    "",
    "# Lesson 12: break Statement",
    "",
    "## Introduction",
    "",
    "In C programming, loops sometimes need to stop before their normal condition becomes false.",
    "",
    "The **break statement** is used to immediately terminate the nearest enclosing loop or switch statement.",
    "",
    "For example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int i;",
    "",
    "    for (i = 1; i <= 10; i++)",
    "    {",
    "        if (i == 6)",
    "        {",
    "            break;",
    "        }",
    "",
    "        printf(\"%d \", i);",
    "    }",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "1 2 3 4 5",
    "```",
    "",
    "When i becomes 6, the break statement is executed and the loop terminates.",
    "",
    "---",
    "",
    "# 1. What Is the break Statement?",
    "",
    "The break statement is a control statement used to terminate the nearest enclosing loop or switch statement.",
    "",
    "It can be used with:",
    "",
    "- for loop",
    "- while loop",
    "- do-while loop",
    "- switch statement",
    "",
    "The syntax is:",
    "",
    "```c",
    "break;",
    "```",
    "",
    "When the break statement is executed, control moves to the statement immediately following the loop or switch statement.",
    "",
    "---",
    "",
    "# 2. Basic Example",
    "",
    "Consider:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int i;",
    "",
    "    for (i = 1; i <= 10; i++)",
    "    {",
    "        if (i == 5)",
    "        {",
    "            break;",
    "        }",
    "",
    "        printf(\"%d \", i);",
    "    }",
    "",
    "    printf(\"\\n\");",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "1 2 3 4",
    "```",
    "",
    "The loop normally allows i to reach 10, but break terminates the loop when i becomes 5.",
    "",
    "---",
    "",
    "# 3. How break Works",
    "",
    "Consider:",
    "",
    "```c",
    "for (i = 1; i <= 10; i++)",
    "{",
    "    if (i == 6)",
    "    {",
    "        break;",
    "    }",
    "",
    "    printf(\"%d \", i);",
    "}",
    "```",
    "",
    "The execution can be understood as:",
    "",
    "```text",
    "i = 1",
    "  ↓",
    "Print 1",
    "  ↓",
    "i = 2",
    "  ↓",
    "Print 2",
    "  ↓",
    "i = 3",
    "  ↓",
    "Print 3",
    "  ↓",
    "i = 4",
    "  ↓",
    "Print 4",
    "  ↓",
    "i = 5",
    "  ↓",
    "Print 5",
    "  ↓",
    "i = 6",
    "  ↓",
    "break",
    "  ↓",
    "Exit loop",
    "```",
    "",
    "Therefore, 6 is not printed.",
    "",
    "---",
    "",
    "# 4. break in a for Loop",
    "",
    "The break statement can be used inside a for loop to terminate it early.",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int i;",
    "",
    "    for (i = 1; i <= 10; i++)",
    "    {",
    "        if (i == 6)",
    "        {",
    "            break;",
    "        }",
    "",
    "        printf(\"%d \", i);",
    "    }",
    "",
    "    printf(\"\\n\");",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "1 2 3 4 5",
    "```",
    "",
    "When i becomes 6, the break statement terminates the for loop.",
    "",
    "---",
    "",
    "# 5. break in a while Loop",
    "",
    "The break statement can also be used inside a while loop.",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int i = 1;",
    "",
    "    while (i <= 10)",
    "    {",
    "        if (i == 6)",
    "        {",
    "            break;",
    "        }",
    "",
    "        printf(\"%d \", i);",
    "        i++;",
    "    }",
    "",
    "    printf(\"\\n\");",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "1 2 3 4 5",
    "```",
    "",
    "When i becomes 6, the break statement terminates the while loop.",
    "",
    "---",
    "",
    "# 6. break in a do-while Loop",
    "",
    "The break statement can also be used inside a do-while loop.",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int i = 1;",
    "",
    "    do",
    "    {",
    "        if (i == 6)",
    "        {",
    "            break;",
    "        }",
    "",
    "        printf(\"%d \", i);",
    "        i++;",
    "    }",
    "    while (i <= 10);",
    "",
    "    printf(\"\\n\");",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "1 2 3 4 5",
    "```",
    "",
    "The break statement terminates the loop when i becomes 6.",
    "",
    "---",
    "",
    "# 7. break With an if Statement",
    "",
    "The break statement is commonly used together with an if statement.",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int i;",
    "",
    "    for (i = 1; i <= 20; i++)",
    "    {",
    "        if (i > 10)",
    "        {",
    "            break;",
    "        }",
    "",
    "        printf(\"%d \", i);",
    "    }",
    "",
    "    printf(\"\\n\");",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "1 2 3 4 5 6 7 8 9 10",
    "```",
    "",
    "The break statement executes when i becomes greater than 10.",
    "",
    "---",
    "",
    "# 8. Using break for Searching",
    "",
    "One common use of break is to stop searching once the required value has been found.",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int target = 7;",
    "    int i;",
    "",
    "    for (i = 1; i <= 10; i++)",
    "    {",
    "        if (i == target)",
    "        {",
    "            printf(\"Value found\\n\");",
    "            break;",
    "        }",
    "    }",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "Value found",
    "```",
    "",
    "Once the target value is found, the loop does not need to continue.",
    "",
    "---",
    "",
    "# 9. Searching an Array Using break",
    "",
    "The break statement can be used to stop an array search after finding the required element.",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int numbers[] = {10, 20, 30, 40, 50};",
    "    int target = 30;",
    "    int found = 0;",
    "    int i;",
    "",
    "    for (i = 0; i < 5; i++)",
    "    {",
    "        if (numbers[i] == target)",
    "        {",
    "            found = 1;",
    "            break;",
    "        }",
    "    }",
    "",
    "    if (found)",
    "    {",
    "        printf(\"Element found\\n\");",
    "    }",
    "    else",
    "    {",
    "        printf(\"Element not found\\n\");",
    "    }",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "Element found",
    "```",
    "",
    "After finding the target element, the loop terminates immediately.",
    "",
    "---",
    "",
    "# 10. break in a switch Statement",
    "",
    "The break statement is also commonly used inside a switch statement.",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int choice;",
    "",
    "    printf(\"Enter your choice: \");",
    "    scanf(\"%d\", &choice);",
    "",
    "    switch (choice)",
    "    {",
    "        case 1:",
    "            printf(\"Option 1 selected\\n\");",
    "            break;",
    "",
    "        case 2:",
    "            printf(\"Option 2 selected\\n\");",
    "            break;",
    "",
    "        case 3:",
    "            printf(\"Option 3 selected\\n\");",
    "            break;",
    "",
    "        default:",
    "            printf(\"Invalid choice\\n\");",
    "    }",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "If the user enters 2, the output is:",
    "",
    "```text",
    "Option 2 selected",
    "```",
    "",
    "The break statement prevents execution from continuing into the following cases.",
    "",
    "---",
    "",
    "# 11. break in Nested Loops",
    "",
    "When break is used inside nested loops, it terminates only the nearest enclosing loop.",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int i;",
    "    int j;",
    "",
    "    for (i = 1; i <= 3; i++)",
    "    {",
    "        for (j = 1; j <= 5; j++)",
    "        {",
    "            if (j == 3)",
    "            {",
    "                break;",
    "            }",
    "",
    "            printf(\"%d \", j);",
    "        }",
    "",
    "        printf(\"\\n\");",
    "    }",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "1 2",
    "1 2",
    "1 2",
    "```",
    "",
    "Here, break terminates the inner loop.",
    "",
    "The outer loop continues with its next iteration.",
    "",
    "---",
    "",
    "# 12. break in an Infinite Loop",
    "",
    "The break statement can be used to terminate an intentionally infinite loop.",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int i = 1;",
    "",
    "    while (1)",
    "    {",
    "        printf(\"%d \", i);",
    "",
    "        if (i == 5)",
    "        {",
    "            break;",
    "        }",
    "",
    "        i++;",
    "    }",
    "",
    "    printf(\"\\nLoop ended\\n\");",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "1 2 3 4 5",
    "Loop ended",
    "```",
    "",
    "The condition 1 is always true, so the loop continues until break is executed.",
    "",
    "---",
    "",
    "# 13. User-Controlled Loop",
    "",
    "The break statement is useful when the user determines when the loop should stop.",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int number;",
    "",
    "    while (1)",
    "    {",
    "        printf(\"Enter a number (0 to stop): \");",
    "        scanf(\"%d\", &number);",
    "",
    "        if (number == 0)",
    "        {",
    "            break;",
    "        }",
    "",
    "        printf(\"You entered: %d\\n\", number);",
    "    }",
    "",
    "    printf(\"Program ended\\n\");",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Example execution:",
    "",
    "```text",
    "Enter a number (0 to stop): 10",
    "You entered: 10",
    "Enter a number (0 to stop): 25",
    "You entered: 25",
    "Enter a number (0 to stop): 0",
    "Program ended",
    "```",
    "",
    "When the user enters 0, the break statement terminates the loop.",
    "",
    "---",
    "",
    "# 14. break and the Normal Loop Condition",
    "",
    "A loop can have its normal termination condition and also contain a break statement.",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int i;",
    "",
    "    for (i = 1; i <= 10; i++)",
    "    {",
    "        if (i == 7)",
    "        {",
    "            break;",
    "        }",
    "",
    "        printf(\"%d \", i);",
    "    }",
    "",
    "    printf(\"\\n\");",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "1 2 3 4 5 6",
    "```",
    "",
    "The loop's normal condition allows it to reach 10, but break terminates it earlier when i becomes 7.",
    "",
    "---",
    "",
    "# 15. break vs continue",
    "",
    "The break statement and continue statement have different purposes.",
    "",
    "break:",
    "",
    "```text",
    "break",
    "  ↓",
    "Terminate the loop",
    "  ↓",
    "Exit the loop",
    "```",
    "",
    "continue:",
    "",
    "```text",
    "continue",
    "  ↓",
    "Skip the remaining statements",
    "of the current iteration",
    "  ↓",
    "Continue with the next iteration",
    "```",
    "",
    "For example:",
    "",
    "```c",
    "if (i == 5)",
    "{",
    "    break;",
    "}",
    "```",
    "",
    "terminates the loop.",
    "",
    "But:",
    "",
    "```c",
    "if (i == 5)",
    "{",
    "    continue;",
    "}",
    "```",
    "",
    "skips the remaining statements of that iteration and continues with the next iteration.",
    "",
    "---",
    "",
    "# 16. Important Rule in Nested Loops",
    "",
    "Consider:",
    "",
    "```c",
    "for (i = 1; i <= 3; i++)",
    "{",
    "    for (j = 1; j <= 3; j++)",
    "    {",
    "        if (j == 2)",
    "        {",
    "            break;",
    "        }",
    "",
    "        printf(\"i = %d, j = %d\\n\", i, j);",
    "    }",
    "}",
    "```",
    "",
    "The break statement belongs to the inner loop.",
    "",
    "Therefore:",
    "",
    "```text",
    "Outer Loop",
    "    ↓",
    "Inner Loop",
    "    ↓",
    "break",
    "    ↓",
    "Exit Inner Loop",
    "    ↓",
    "Outer Loop continues",
    "```",
    "",
    "The break statement does not automatically terminate the outer loop.",
    "",
    "---",
    "",
    "# 17. Practical Example — Finding the First Even Number",
    "",
    "The break statement can be used when only the first matching value is required.",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int numbers[] = {7, 9, 11, 14, 18};",
    "    int i;",
    "",
    "    for (i = 0; i < 5; i++)",
    "    {",
    "        if (numbers[i] % 2 == 0)",
    "        {",
    "            printf(\"First even number = %d\\n\", numbers[i]);",
    "            break;",
    "        }",
    "    }",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "First even number = 14",
    "```",
    "",
    "Once 14 is found, the loop terminates.",
    "",
    "---",
    "",
    "# 18. Practical Example — Stop at a Negative Number",
    "",
    "Example:",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int numbers[] = {10, 20, 30, -5, 40};",
    "    int i;",
    "",
    "    for (i = 0; i < 5; i++)",
    "    {",
    "        if (numbers[i] < 0)",
    "        {",
    "            break;",
    "        }",
    "",
    "        printf(\"%d \", numbers[i]);",
    "    }",
    "",
    "    printf(\"\\n\");",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Output:",
    "",
    "```text",
    "10 20 30",
    "```",
    "",
    "When the negative number is encountered, break terminates the loop.",
    "",
    "---",
    "",
    "# 19. Complete Example",
    "",
    "The following program demonstrates a user-controlled loop using break.",
    "",
    "```c",
    "#include <stdio.h>",
    "",
    "int main(void)",
    "{",
    "    int number;",
    "",
    "    while (1)",
    "    {",
    "        printf(\"Enter a number (0 to exit): \");",
    "        scanf(\"%d\", &number);",
    "",
    "        if (number == 0)",
    "        {",
    "            break;",
    "        }",
    "",
    "        printf(\"Square = %d\\n\", number * number);",
    "    }",
    "",
    "    printf(\"Program terminated.\\n\");",
    "",
    "    return 0;",
    "}",
    "```",
    "",
    "Example output:",
    "",
    "```text",
    "Enter a number (0 to exit): 4",
    "Square = 16",
    "Enter a number (0 to exit): 7",
    "Square = 49",
    "Enter a number (0 to exit): 0",
    "Program terminated.",
    "```",
    "",
    "The loop continues until the user enters 0.",
    "",
    "---",
    "",
    "# Common Beginner Mistakes",
    "",
    "## Mistake 1 — Thinking break Skips an Iteration",
    "",
    "The break statement does not simply skip the current iteration.",
    "",
    "It terminates the nearest enclosing loop.",
    "",
    "---",
    "",
    "## Mistake 2 — Expecting break to Exit All Nested Loops",
    "",
    "In nested loops, break terminates only the nearest enclosing loop.",
    "",
    "---",
    "",
    "## Mistake 3 — Forgetting break in switch",
    "",
    "Without break, execution can continue into subsequent cases.",
    "",
    "For example:",
    "",
    "```c",
    "switch (choice)",
    "{",
    "    case 1:",
    "        printf(\"One\\n\");",
    "",
    "    case 2:",
    "        printf(\"Two\\n\");",
    "}",
    "```",
    "",
    "If choice is 1, execution can continue into case 2.",
    "",
    "A break can be used when that fall-through is not intended.",
    "",
    "---",
    "",
    "## Mistake 4 — Not Understanding Which Loop break Affects",
    "",
    "When loops are nested, identify the nearest enclosing loop before using break.",
    "",
    "---",
    "",
    "# Lesson Summary",
    "",
    "In this lesson, you learned:",
    "",
    "- The break statement immediately terminates the nearest enclosing loop or switch.",
    "- The syntax is:",
    "",
    "```c",
    "break;",
    "```",
    "",
    "- break can be used with for loops.",
    "- break can be used with while loops.",
    "- break can be used with do-while loops.",
    "- break can be used with switch statements.",
    "- break is useful when searching for a value.",
    "- break can terminate an infinite loop.",
    "- break is useful when a user-controlled condition determines when a loop should stop.",
    "- In nested loops, break terminates only the nearest enclosing loop.",
    "- break and continue have different purposes.",
    "",
    "The key idea is:",
    "",
    "```text",
    "Loop",
    "  ↓",
    "Early termination condition",
    "  ↓",
    "break",
    "  ↓",
    "Exit nearest enclosing loop",
    "```",
    "",
    "---",
    "",
    "# Module 3 Progress",
    "",
    "✓ Lesson 1 — Conditional Statements",
    "✓ Lesson 2 — if Statement",
    "✓ Lesson 3 — if-else Statement",
    "✓ Lesson 4 — else-if Ladder",
    "✓ Lesson 5 — Nested if",
    "✓ Lesson 6 — switch Statement",
    "✓ Lesson 7 — Conditional Operator",
    "✓ Lesson 8 — for Loop",
    "✓ Lesson 9 — while Loop",
    "✓ Lesson 10 — do-while Loop",
    "✓ Lesson 11 — Nested Loops",
    "→ Lesson 12 — break Statement",
    "  Lesson 13 — continue Statement",
    "  Lesson 14 — goto Statement and Loop Control",
    "  Lesson 15 — Mini Project",
    "",
    "Lesson 12 Complete",
    "",
    "Next: Lesson 13 — continue Statement.",
    ""
  ].join("\\n")
};

export default lesson12;