export const DEEP_LEARNING_STRUCTURE = [
  {
    id: "module1",
    title: "Deep Learning Foundations",
    lessons: [
      ["lesson1", "Introduction to Deep Learning"],
      ["lesson2", "Tensor Operations"],
      ["lesson3", "Data Preprocessing"],
      ["lesson4", "Linear Algebra for Deep Learning"],
      ["lesson5", "Calculus for Deep Learning"],
      ["lesson6", "Automatic Differentiation"],
      ["lesson7", "Probability and Statistics"],
      ["lesson8", "Deep Learning Workflow"],
    ],
  },

  {
    id: "module2",
    title: "Neural Networks and Learning",
    lessons: [
      ["lesson1", "Linear Regression"],
      ["lesson2", "Image Classification Dataset"],
      ["lesson3", "Base Classification Model"],
      ["lesson4", "Softmax Regression"],
      ["lesson5", "Image Classification Implementation"],
      ["lesson6", "Multilayer Perceptrons"],
      ["lesson7", "Activation Functions"],
      ["lesson8", "Forward and Backward Propagation"],
      ["lesson9", "Computational Graphs"],
      ["lesson10", "Numerical Stability"],
      ["lesson11", "Model Initialization"],
      ["lesson12", "Parameter Initialization"],
      ["lesson13", "Layers and Modules"],
      ["lesson14", "Custom Layers"],
      ["lesson15", "Parameter Sharing"],
      ["lesson16", "Dropout and Regularization"],
    ],
  },

  {
    id: "module3",
    title: "Convolutional Neural Networks",
    lessons: [
      ["lesson1", "Convolutional Principles"],
      ["lesson2", "Convolutions for Images"],
      ["lesson3", "Padding and Stride"],
      ["lesson4", "Multiple Channels"],
      ["lesson5", "Pooling"],
      ["lesson6", "LeNet"],
      ["lesson7", "Deep CNN Design"],
      ["lesson8", "AlexNet"],
      ["lesson9", "VGG"],
      ["lesson10", "Network in Network"],
      ["lesson11", "GoogLeNet"],
      ["lesson12", "Batch Normalization"],
      ["lesson13", "ResNet"],
      ["lesson14", "DenseNet"],
      ["lesson15", "Modern CNN Practices"],
    ],
  },

  {
    id: "module4",
    title: "Sequence Models and Transformers",
    lessons: [
      ["lesson1", "Sequence Data and Temporal Dependencies"],
      ["lesson2", "Recurrent Neural Networks"],
      ["lesson3", "RNNs from Scratch"],
      ["lesson4", "RNN Language Models"],
      ["lesson5", "Training RNNs and Gradient Problems"],
      ["lesson6", "Concise RNN Implementation"],
      ["lesson7", "Gated Recurrent Units"],
      ["lesson8", "Long Short-Term Memory"],
      ["lesson9", "Deep Recurrent Neural Networks"],
      ["lesson10", "Bidirectional RNNs"],
      ["lesson11", "Sequence-to-Sequence Problems"],
      ["lesson12", "Machine Translation Dataset"],
      ["lesson13", "Encoder-Decoder Architecture"],
      ["lesson14", "Sequence-to-Sequence Learning"],
      ["lesson15", "Beam Search"],
      ["lesson16", "Attention Mechanisms"],
      ["lesson17", "Multi-Head Attention"],
      ["lesson18", "Self-Attention and Positional Encoding"],
      ["lesson19", "The Transformer Architecture"],
      ["lesson20", "Transformers for Vision"],
      ["lesson21", "Large-Scale Pretraining"],
      ["lesson22", "Transformer Applications"],
    ],
  },

  {
    id: "module5",
    title: "Advanced Deep Learning and Training",
    lessons: [
      ["lesson1", "Optimization and Deep Learning"],
      ["lesson2", "Convexity"],
      ["lesson3", "Gradient Descent"],
      ["lesson4", "Stochastic Gradient Descent"],
      ["lesson5", "Minibatch SGD"],
      ["lesson6", "Momentum"],
      ["lesson7", "AdaGrad"],
      ["lesson8", "RMSProp"],
      ["lesson9", "AdaDelta"],
      ["lesson10", "Adam"],
      ["lesson11", "Learning Rate Scheduling"],
      ["lesson12", "Compilers and Interpreters"],
      ["lesson13", "Asynchronous Computation"],
      ["lesson14", "Automatic Parallelism"],
      ["lesson15", "Deep Learning Hardware"],
      ["lesson16", "GPU Computing"],
      ["lesson17", "Multiple GPU Training"],
      ["lesson18", "Data Parallelism"],
      ["lesson19", "Parameter Servers"],
    ],
  },

  {
    id: "module6",
    title: "Computer Vision",
    lessons: [
      ["lesson1", "Image Augmentation"],
      ["lesson2", "Fine-Tuning"],
      ["lesson3", "Object Detection and Bounding Boxes"],
      ["lesson4", "Anchor Boxes"],
      ["lesson5", "Multiscale Object Detection"],
      ["lesson6", "Object Detection Dataset"],
      ["lesson7", "Single Shot Multibox Detection"],
      ["lesson8", "R-CNN and Region-Based Detection"],
      ["lesson9", "Semantic Segmentation"],
      ["lesson10", "Transposed Convolution"],
      ["lesson11", "Fully Convolutional Networks"],
      ["lesson12", "Neural Style Transfer Foundations"],
      ["lesson13", "Image Generation Techniques"],
      ["lesson14", "Dog Breed Identification"],
      ["lesson15", "Computer Vision Pipelines"],
      ["lesson16", "Advanced Object Detection"],
      ["lesson17", "Advanced Segmentation"],
      ["lesson18", "Neural Style Transfer"],
      ["lesson19", "Vision System Design"],
      ["lesson20", "Computer Vision Capstone"],
    ],
  },
] as const;

export default DEEP_LEARNING_STRUCTURE;