export const MACHINE_LEARNING_STRUCTURE = [
  {
    id: "module1",
    title: "Module 01 — Machine Learning Foundations",
    lessons: [
      ["lesson1", "What Is Machine Learning?"],
      ["lesson2", "Why Machine Learning?"],
      ["lesson3", "Types of Machine Learning"],
      ["lesson4", "Supervised vs Unsupervised Learning"],
      ["lesson5", "Classification vs Regression"],
      ["lesson6", "Understanding ML Problems"],
      ["lesson7", "Data, Samples, Features and Targets"],
      ["lesson8", "Training, Validation and Test Data"],
      ["lesson9", "Generalization"],
      ["lesson10", "Overfitting and Underfitting"],
      ["lesson11", "Model Complexity and Dataset Size"],
      ["lesson12", "Python Environment for Machine Learning"],
      ["lesson13", "NumPy, Pandas and Matplotlib for ML"],
      ["lesson14", "Introduction to scikit-learn"],
      ["lesson15", "Your First Machine Learning Model"],
    ],
    extras: [
      ["about", "About This Module"],
      ["practice", "Module Practice"],
      ["project", "Module Project"],
    ],
  },

  {
    id: "module2",
    title: "Module 02 — Supervised Machine Learning",
    lessons: [
      ["lesson1", "k-Nearest Neighbors"],
      ["lesson2", "Distance and Similarity"],
      ["lesson3", "kNN Classification"],
      ["lesson4", "kNN Regression"],
      ["lesson5", "Linear Regression"],
      ["lesson6", "Linear Regression Mathematics"],
      ["lesson7", "Loss Functions and Mean Squared Error"],
      ["lesson8", "Gradient Descent"],
      ["lesson9", "Logistic Regression"],
      ["lesson10", "Probability and Classification"],
      ["lesson11", "Naive Bayes"],
      ["lesson12", "Decision Trees"],
      ["lesson13", "Tree Splitting and Impurity"],
      ["lesson14", "Random Forests and Tree Ensembles"],
      ["lesson15", "Support Vector Machines"],
      ["lesson16", "Kernels and Nonlinear Classification"],
      ["lesson17", "Introduction to Ensemble Learning"],
      ["lesson18", "Choosing a Supervised Learning Algorithm"],
    ],
  },

  {
    id: "module3",
    title: "Module 03 — Unsupervised Learning & Data Preprocessing",
    lessons: [
      ["lesson1", "What Is Unsupervised Learning?"],
      ["lesson2", "Challenges in Unsupervised Learning"],
      ["lesson3", "Data Scaling and Standardization"],
      ["lesson4", "Normalization and Transformation"],
      ["lesson5", "Applying Preprocessing with scikit-learn"],
      ["lesson6", "Why Preprocessing Matters"],
      ["lesson7", "Dimensionality Reduction"],
      ["lesson8", "Principal Component Analysis (PCA)"],
      ["lesson9", "PCA Mathematics and Intuition"],
      ["lesson10", "Non-Negative Matrix Factorization"],
      ["lesson11", "Manifold Learning"],
      ["lesson12", "t-SNE Visualization"],
      ["lesson13", "Clustering"],
      ["lesson14", "k-Means Clustering"],
      ["lesson15", "Agglomerative Clustering"],
      ["lesson16", "DBSCAN"],
      ["lesson17", "Comparing Clustering Algorithms"],
      ["lesson18", "Choosing an Unsupervised Learning Method"],
    ],
  },

  {
    id: "module4",
    title: "Module 04 — Feature Engineering & Representation",
    lessons: [
      ["lesson1", "Why Data Representation Matters"],
      ["lesson2", "Numerical and Categorical Features"],
      ["lesson3", "Encoding Categorical Variables"],
      ["lesson4", "One-Hot Encoding"],
      ["lesson5", "Handling Numerical Features"],
      ["lesson6", "Binning and Discretization"],
      ["lesson7", "Polynomial Features"],
      ["lesson8", "Feature Interactions"],
      ["lesson9", "Nonlinear Feature Transformations"],
      ["lesson10", "Feature Scaling"],
      ["lesson11", "Feature Selection"],
      ["lesson12", "Univariate Feature Selection"],
      ["lesson13", "Model-Based Feature Selection"],
      ["lesson14", "Iterative Feature Selection"],
      ["lesson15", "Using Domain and Expert Knowledge"],
      ["lesson16", "Building a Complete Feature Engineering Workflow"],
    ],
  },

  {
    id: "module5",
    title: "Module 05 — Model Evaluation, Tuning & Pipelines",
    lessons: [
      ["lesson1", "Why Model Evaluation Matters"],
      ["lesson2", "Cross-Validation"],
      ["lesson3", "k-Fold Cross-Validation"],
      ["lesson4", "Stratified Cross-Validation"],
      ["lesson5", "Cross-Validation with scikit-learn"],
      ["lesson6", "Evaluation Metrics"],
      ["lesson7", "Classification Metrics"],
      ["lesson8", "Precision, Recall and F1 Score"],
      ["lesson9", "ROC Curve and AUC"],
      ["lesson10", "Multiclass Evaluation"],
      ["lesson11", "Regression Metrics"],
      ["lesson12", "Choosing the Right Metric"],
      ["lesson13", "Hyperparameters"],
      ["lesson14", "Grid Search"],
      ["lesson15", "Randomized Search"],
      ["lesson16", "Avoiding Validation Overfitting"],
      ["lesson17", "Pipelines"],
      ["lesson18", "Building ML Pipelines with scikit-learn"],
      ["lesson19", "Pipelines with Preprocessing"],
      ["lesson20", "Grid Search with Pipelines"],
      ["lesson21", "Comparing Multiple Models"],
      ["lesson22", "End-to-End Model Optimization"],
    ],
  },

  {
    id: "module6",
    title: "Module 06 — Text Machine Learning & Real-World ML",
    lessons: [
      ["lesson1", "Introduction to Machine Learning with Text"],
      ["lesson2", "Representing Text as Data"],
      ["lesson3", "Bag-of-Words"],
      ["lesson4", "Count Vectorization"],
      ["lesson5", "Stopwords"],
      ["lesson6", "TF-IDF"],
      ["lesson7", "n-Grams"],
      ["lesson8", "Tokenization"],
      ["lesson9", "Stemming and Lemmatization"],
      ["lesson10", "Text Classification"],
      ["lesson11", "Sentiment Analysis"],
      ["lesson12", "Topic Modeling"],
      ["lesson13", "Document Clustering"],
      ["lesson14", "Latent Dirichlet Allocation"],
      ["lesson15", "Humans in the ML Loop"],
      ["lesson16", "Approaching a Real ML Problem"],
      ["lesson17", "From Prototype to Production"],
      ["lesson18", "Testing Machine Learning Systems"],
      ["lesson19", "Building Reusable ML Components"],
      ["lesson20", "Scaling Machine Learning Systems"],
      ["lesson21", "Complete End-to-End ML Workflow"],
    ],
  },
];