const lesson9 = {

  id: "lesson9",

  title: "Writing, Compiling, and Running First Java Program",

  content: `

# Writing, Compiling, and Running First Java Program


## Introduction


After installing the Java Development Kit and setting up the Java development environment, the next step is learning how to create and execute a Java program.


Every Java application follows a fixed execution process:


- Writing source code.
- Compiling source code.
- Generating bytecode.
- Executing bytecode using JVM.
- Producing output.



## Creating a Java Program


Java programs are written using a text editor or Integrated Development Environment (IDE).


Java source files are stored with the extension:


.java



Example:


HelloWorld.java



## First Java Program


Example:


class HelloWorld

{

    public static void main(String[] args)

    {

        System.out.println("Hello Java");

    }

}



## Understanding the First Program



## Class Declaration


Example:


class HelloWorld



A class is a blueprint that contains variables and methods.


Every Java program must contain at least one class.



## Main Method


Example:


public static void main(String[] args)



The main method is the starting point of Java program execution.


The JVM searches for the main method when running a Java application.



## public Keyword


The public keyword allows the JVM to access the main method from outside the class.



## static Keyword


The static keyword allows the JVM to call the main method without creating an object.



## void Keyword


The void keyword indicates that the method does not return any value.



## String[] args


String array stores command-line arguments passed to the program.



## System.out.println()


The println() method is used to display output on the console.


Example:


System.out.println("Hello Java");



## Saving Java Program


The Java file name should match the class name.


Example:


Class name:


HelloWorld


File name:


HelloWorld.java



## Compilation Process


Java source code cannot be directly executed by the computer.


It must first be converted into bytecode.



The Java compiler performs this conversion.



## Java Compiler


The Java compiler is called:


javac



Syntax:


javac filename.java



Example:


javac HelloWorld.java



After successful compilation, a new file is created:


HelloWorld.class



## Bytecode


Bytecode is an intermediate code generated by the Java compiler.


It is platform independent and can run on any system that has JVM.



## Running Java Program


The bytecode file is executed by JVM.



Command:


java ClassName



Example:


java HelloWorld



Output:


Hello Java



## Complete Java Execution Flow


The complete process is:



Java Source Code

↓

Java Compiler (javac)

↓

Bytecode (.class)

↓

Java Virtual Machine (JVM)

↓

Machine Code

↓

Program Output



## Running Java Program Using IDE


Modern IDEs make Java execution easier.


Steps:


1. Create a Java project.

2. Create a Java class.

3. Write Java code.

4. Click the Run button.

5. View output.



## Running Java Program Using Command Line


Java programs can also be executed using terminal commands.



Compile:


javac Program.java



Run:


java Program



## Common Errors While Running Java Programs



## Class Name Error


Cause:


Class name and file name are different.



Solution:


Keep the same name for both class and file.



## Missing Main Method


Cause:


JVM cannot find the entry point.



Solution:


Write the main method correctly.



## Syntax Errors


Cause:


Incorrect Java syntax.


Examples:


- Missing semicolon.
- Incorrect brackets.
- Wrong keywords.



## Compilation Errors


Compilation errors occur when the compiler finds problems in source code.


The program must be corrected before execution.



## Importance of First Java Program


The first Java program helps you understand:


- Java syntax.
- Class structure.
- Main method.
- Compilation process.
- Program execution.



## Real-World Application


The same development process is used while creating:


### Enterprise Applications


Large business software systems.


### Banking Applications


Secure transaction systems.


### Android Applications


Mobile applications.


### Cloud Applications


Distributed software solutions.



## Key Points


Remember:


- Java programs use .java extension.
- javac converts source code into bytecode.
- Bytecode is stored in .class files.
- JVM executes bytecode.
- main() method starts execution.
- Class name and file name should match.


Writing, compiling, and running the first Java program is the foundation for learning advanced Java programming concepts.

`

};


export default lesson9;