const lesson6 = {

  id: "lesson6",

  title: "Java Architecture",

  content: `

# Java Architecture


## Introduction


Java architecture explains how a Java program is converted from source code into executable instructions.


The architecture of Java is designed to provide:


- Platform independence.
- Security.
- Portability.
- Efficient execution.


The main component responsible for Java execution is the Java Virtual Machine (JVM).



## Java Execution Architecture


The complete execution process contains several stages:


Java Source Code

↓

Java Compiler

↓

Bytecode

↓

Class Loader

↓

Bytecode Verifier

↓

Runtime Memory

↓

Execution Engine

↓

Machine Code

↓

Output



# Components of Java Architecture


Java architecture mainly consists of:



## 1. Java Source Code


The program written by a developer is called source code.


Java source files use the extension:


.java


Example:


HelloWorld.java



## 2. Java Compiler


The Java compiler converts source code into bytecode.


The compiler command is:


javac filename.java



Example:


javac HelloWorld.java



After compilation, a bytecode file is created:


HelloWorld.class



## 3. Bytecode


Bytecode is an intermediate code generated by the Java compiler.


It is not directly executed by the operating system.


It is executed by JVM.



## 4. Class Loader


The Class Loader loads required class files into JVM memory.


Responsibilities:


- Loading classes.
- Checking class availability.
- Preparing classes for execution.



## 5. Bytecode Verifier


The Bytecode Verifier checks the generated bytecode before execution.


It ensures:


- Security.
- Correctness.
- No illegal operations.



## 6. Runtime Memory Area


JVM creates memory areas to store program information.


Important memory areas include:



### Method Area


Stores:


- Class information.
- Static variables.
- Method details.



### Heap Area


Stores:


- Objects.
- Instance variables.



### Stack Area


Stores:


- Local variables.
- Method calls.



### PC Register


Stores the address of the current instruction.



### Native Method Stack


Stores native method information.



## 7. Execution Engine


The Execution Engine executes Java bytecode.


It contains:



### Interpreter


Reads and executes bytecode instructions one by one.



### Just-In-Time Compiler (JIT)


Converts frequently executed bytecode into machine code for better performance.



### Garbage Collector


Automatically removes unused objects from memory.



# Role of JVM in Java Architecture


JVM provides:


- Platform independence.
- Memory management.
- Security.
- Program execution.
- Performance optimization.



# Platform Independence Through Architecture


Java follows:


"Write Once, Run Anywhere"


The same bytecode can run on different operating systems because each platform has its own JVM.



Example:


Java Program

↓

Bytecode

↓

Windows JVM

Linux JVM

Mac JVM



# Advantages of Java Architecture


Java architecture provides:


- Secure execution.
- Automatic memory management.
- Portability.
- Better performance.
- Reliable applications.



# Real-World Usage


Java architecture is used in:


- Banking systems.
- Enterprise applications.
- Cloud services.
- Android applications.
- Web servers.



# Key Points


Remember:


- Java source code is converted into bytecode.
- JVM executes bytecode.
- Class Loader loads classes.
- Bytecode Verifier provides security.
- Execution Engine runs the program.
- Garbage Collector manages memory.


Java architecture is the foundation that makes Java powerful, secure, and platform independent.

`

};


export default lesson6;