const lesson7 = {
  id: "lesson7",
  moduleId: "module6",

  title: "Model Selection, Parameters & Cost Optimization",

  subtitle:
    "Learn how to select models for application requirements while balancing quality, latency, context capacity, throughput, and cost.",

  description:
    "Choosing an LLM is an engineering decision rather than simply choosing the largest available model. This lesson explains model capability, parameter behavior, context limits, latency, throughput, token economics, routing, caching, batching, and practical cost optimization.",

  difficulty: "Intermediate → Advanced",

  estimatedTime: "3–4 hours",

  learningObjectives: [
    "Understand the major dimensions of model selection.",
    "Distinguish model capability from model size.",
    "Understand input and output token costs.",
    "Understand latency and throughput.",
    "Understand context-window requirements.",
    "Compare quality, cost, and latency tradeoffs.",
    "Understand model routing.",
    "Understand caching and batching.",
    "Estimate application-level LLM cost.",
    "Design a model-selection strategy."
  ],

  sections: [
    {
      id: "01",
      title: "Model Selection Is an Engineering Problem",
      content: `
A model should be selected according to the application's requirements.

Important dimensions include:

QUALITY
LATENCY
COST
CONTEXT CAPACITY
THROUGHPUT
RELIABILITY
MODALITY
TOOL-CALLING SUPPORT
STRUCTURED OUTPUT SUPPORT

There is usually no single model that is optimal for every workload.
`
    },

    {
      id: "02",
      title: "Capability vs Model Size",
      content: `
A larger model may provide stronger performance on some tasks, but model
size alone does not determine application quality.

Application quality depends on:

model capability
+
prompt quality
+
context quality
+
retrieval quality
+
tool usage
+
validation
+
evaluation

Therefore:

Better application ≠ simply larger model.
`
    },

    {
      id: "03",
      title: "Task-Based Model Selection",
      comparison: [
        {
          task: "Simple classification",
          considerations: [
            "low latency",
            "low cost",
            "structured output"
          ]
        },
        {
          task: "Complex reasoning",
          considerations: [
            "reasoning capability",
            "accuracy",
            "larger context when required"
          ]
        },
        {
          task: "High-volume summarization",
          considerations: [
            "throughput",
            "cost per request",
            "consistent output"
          ]
        },
        {
          task: "Real-time assistant",
          considerations: [
            "low TTFT",
            "streaming",
            "latency"
          ]
        }
      ]
    },

    {
      id: "04",
      title: "Input and Output Tokens",
      content: `
LLM usage commonly involves two major token categories:

INPUT TOKENS
Tokens sent to the model.

OUTPUT TOKENS
Tokens generated by the model.

Long prompts, retrieved documents, and conversation history can therefore
increase input usage.

Long generated answers increase output usage.
`
    },

    {
      id: "05",
      title: "Cost Estimation",

      formula: `
Input cost =
input tokens × input price

Output cost =
output tokens × output price

Total cost =
input cost + output cost
`,

      content: `
For a simplified example:

Input:
10,000 tokens

Output:
2,000 tokens

If input price is P_in per token and output price is P_out per token:

Cost =
10,000 × P_in
+
2,000 × P_out

Production systems should calculate cost using the actual provider pricing
for the selected model.
`
    },

    {
      id: "06",
      title: "Latency",
      formula: `
Total latency ≈
network latency
+
queueing
+
model processing
+
output generation
`,

      content: `
Latency affects interactive applications directly.

Important measurements include:

TTFT
Time to first token.

Total latency
Time until the complete response.

P50
Median latency.

P95
Latency below which approximately 95% of measured requests fall.

P99
Latency below which approximately 99% of measured requests fall.
`
    },

    {
      id: "07",
      title: "Throughput",

      formula: `
Throughput =
completed requests / unit time
`,

      content: `
A batch-processing system may care more about throughput than individual
request latency.

Examples:

• document summarization
• dataset processing
• embedding generation
• offline classification
`
    },

    {
      id: "08",
      title: "Context Window Requirements",
      content: `
Context capacity matters when an application sends:

• long conversations
• retrieved documents
• large files
• multiple tool results
• system instructions

But a larger context window does not mean an application should always
send more context.

More context can increase:

• cost
• latency
• noise
• processing requirements
`
    },

    {
      id: "09",
      title: "Model Routing",
      content: `
Model routing selects different models for different tasks.

Example:

                USER REQUEST
                     ↓
                CLASSIFIER
                /         \
          SIMPLE           COMPLEX
             ↓                ↓
        SMALL MODEL       LARGE MODEL

This can reduce cost while preserving capability where it matters.
`
    },

    {
      id: "10",
      title: "Caching",
      content: `
Caching avoids repeating expensive work.

Example:

USER
 ↓
REQUEST
 ↓
CACHE LOOKUP
 /       \
HIT      MISS
 ↓         ↓
RESULT    MODEL
            ↓
          CACHE
            ↓
          RESULT

Potential cache candidates include:

• repeated prompts
• deterministic transformations
• retrieved context
• expensive intermediate results
`
    },

    {
      id: "11",
      title: "Batching",
      content: `
If multiple independent tasks can be processed together, batching may
improve infrastructure efficiency.

Example:

Document 1
Document 2
Document 3
Document 4

        ↓

Batch processing

However, batching may increase individual request waiting time, so the
tradeoff must be measured.
`
    },

    {
      id: "12",
      title: "Output Length Control",
      content: `
Generated output consumes tokens.

Applications can reduce unnecessary generation by specifying:

• concise response requirements
• output limits
• structured schemas
• explicit stopping conditions

The objective is not simply minimum output.

The objective is:

sufficient output
+
useful information
+
acceptable cost
`
    },

    {
      id: "13",
      title: "Cost Optimization Strategies",
      content: `
Common strategies include:

1. Choose an appropriate model.
2. Reduce unnecessary prompt content.
3. Limit unnecessary output.
4. Cache repeated work.
5. Route simple tasks to smaller models.
6. Batch suitable workloads.
7. Monitor token usage.
8. Remove redundant context.
9. Evaluate before changing models.
10. Optimize the complete application rather than only the API call.
`
    },

    {
      id: "14",
      title: "Quality-Cost Tradeoff",
      content: `
Consider two models:

Model A:
high quality
high cost
higher latency

Model B:
moderate quality
lower cost
lower latency

The correct choice depends on the application's quality requirement.

Therefore model selection should be connected to an evaluation dataset.
`
    },

    {
      id: "15",
      title: "Model Fallbacks",
      content: `
A production application can define fallback behavior.

PRIMARY MODEL
      ↓
failure?
 /       \
NO       YES
 ↓        ↓
RESULT   FALLBACK
           ↓
         RESULT

Fallbacks can address:

• temporary provider errors
• capacity problems
• unsupported features
• availability issues

Fallback behavior should be tested rather than assumed.
`
    },

    {
      id: "16",
      title: "Model Selection Workflow",
      content: `
REQUIREMENTS
     ↓
DEFINE EVALUATION DATASET
     ↓
TEST CANDIDATE MODELS
     ↓
MEASURE QUALITY
     ↓
MEASURE LATENCY
     ↓
MEASURE COST
     ↓
SELECT CONFIGURATION
     ↓
MONITOR IN PRODUCTION
     ↓
RE-EVALUATE
`
    }
  ],

  codeExamples: [
    {
      title: "Simple Cost Estimator",
      language: "python",
      code: `
def estimate_cost(
    input_tokens,
    output_tokens,
    input_price,
    output_price
):
    input_cost = (
        input_tokens * input_price
    )

    output_cost = (
        output_tokens * output_price
    )

    return input_cost + output_cost
`
    },

    {
      title: "Simple Model Router",
      language: "python",
      code: `
def choose_model(task_complexity):
    if task_complexity == "simple":
        return "small-model"

    if task_complexity == "complex":
        return "large-model"

    return "default-model"
`
    },

    {
      title: "Latency Measurement",
      language: "python",
      code: `
import time


def measure_call(call):
    start = time.perf_counter()

    result = call()

    elapsed = (
        time.perf_counter() - start
    )

    return result, elapsed
`
    }
  ],

  exercises: [
    {
      type: "conceptual",
      question:
        "Why is model size alone insufficient for selecting a production model?"
    },
    {
      type: "calculation",
      question:
        "Calculate total token cost when a request uses 8,000 input tokens and 1,500 output tokens."
    },
    {
      type: "architecture",
      question:
        "Design a routing system that sends simple questions to a smaller model and complex questions to a larger model."
    },
    {
      type: "analysis",
      question:
        "Why can sending a very large context increase both cost and latency?"
    }
  ],

  codingExercises: [
    "Build an LLM cost estimator.",
    "Build a model-routing function.",
    "Create a token-usage logger.",
    "Implement a basic response cache.",
    "Measure P50 and P95 latency from sample requests.",
    "Create a model comparison report."
  ],

  interviewQuestions: [
    "What factors should influence model selection?",
    "What are input and output tokens?",
    "How is LLM cost estimated?",
    "What is TTFT?",
    "What is throughput?",
    "What is model routing?",
    "Why use caching?",
    "What is batching?",
    "Why can excessive context be harmful?",
    "How would you compare two candidate models?"
  ],

  commonMistakes: [
    "Always choosing the largest model.",
    "Ignoring token usage.",
    "Ignoring output length.",
    "Optimizing cost without measuring quality.",
    "Optimizing latency without measuring correctness.",
    "Sending unnecessary context.",
    "Adding routing without evaluation.",
    "Assuming caching is always safe."
  ],

  summary: [
    "Model selection should be requirement-driven.",
    "Quality, latency, cost, context, and throughput are important dimensions.",
    "Token usage directly affects API cost.",
    "TTFT and total latency measure different user-experience properties.",
    "Routing can assign different workloads to different models.",
    "Caching can eliminate repeated computation.",
    "Batching can improve throughput for suitable workloads.",
    "Model selection should be validated with real evaluation data."
  ],

  keyTakeaways: [
    "Choose models based on measurable application requirements.",
    "Measure quality, cost, latency, and throughput together.",
    "Use routing when workloads have different capability requirements.",
    "Control unnecessary context and output.",
    "Never optimize cost or latency without checking application quality."
  ]
};

export default lesson7;